#!/bin/sh
#     ______     __          ______                    
#    / ____/____/ /_  ____ _/ ____/___  ____  ________ 
#   / __/ / ___/ __ \/ __ `/ / __/ __ \/ __ \/ ___/ _ \
#  / /___/ /  / / / / /_/ / /_/ / /_/ / /_/ (__  )  __/
# /_____/_/  /_/ /_/\__,_/\____/\____/\____/____/\___/ 

usage() {
    cat - <<EOF
Usage:
    lunchbox push [DST_FOLDER]
    lunchbox pull [DST_FOLDER]
    Requirements:
    Add host "lunchbox" in ~/.ssh/config
    Specifiy workspace path: export LUNCHBOX_WS=/workspace/<username>
EOF
}

push() {
    DIRNAME=$(basename `pwd`)
    if [ "$#" -gt 0 ]; then
        DIRNAME="$1"
    fi
    rsync -rlptz --progress --delete --exclude=.git . "lunchbox:$LUNCHBOX_WS/$DIRNAME"
}

pull() {
    DIRNAME=$(basename `pwd`)
    if [ "$#" -gt 0 ]; then
        DIRNAME="$1"
    fi
    rsync -rlptzh --progress --delete --exclude=.git "lunchbox:$LUNCHBOX_WS/$DIRNAME/" .
}

if [ "$#" -eq 0 ]; then
    usage
    exit 1
fi

if [ "$#" -eq 1 ]; then
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        usage
        exit 0
    fi
    if [ "$1" = "push" ]; then
        push
        exit 0
    fi
    if [ "$1" = "pull" ]; then
        pull
        exit 0
    fi
fi

if [ "$#" -eq 2 ]; then
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        usage
        exit 0
    fi
    if [ "$1" = "push" ]; then
        push "$2"
        exit 0
    fi
    if [ "$1" = "pull" ]; then
        pull "$2"
        exit 0
    fi
fi

if [ "$#" -gt 2 ]; then
    usage
    exit 0
fi
